import {
  home,
  overview,
  getStarted,
  layout,
  button,
  linkButton,
  badge,
  tags,
  alert,
  typo,
  avatar,
  banner,
  fieldset,
  figure,
  fullscreen,
  grid,
  list,
  breadcrum,
  modal,
  spinner,
  table,
  textHighlight,
  hooks,
} from "../images";

const routes = [
  {
    id: Math.random(),
    label: "Home",
    path: "/",
    icons: home,
  },
  {
    id: Math.random(),
    label: "Components Overview",
    path: "/componentsOverview",
    icons: overview,
  },
  {
    id: Math.random(),
    label: "Get Started",
    path: "/getStarted",
    icons: getStarted,
    subMenu: [{ id: Math.random(), label: "Introduction", path: "/getStarted/introduction" }],
  },
  {
    id: Math.random(),
    label: "Layout",
    path: "/layout",
    icons: layout,
  },
  {
    id: Math.random(),
    label: "Typography",
    path: "/typography",
    icons: typo,
  },
  {
    id: Math.random(),
    label: "Button",
    path: "/button",
    icons: button,
  },
  {
    id: Math.random(),
    label: "Link Button",
    path: "/linkButton",
    icons: linkButton,
  },
  {
    id: Math.random(),
    label: "Badge",
    path: "/badge",
    icons: badge,
  },
  {
    id: Math.random(),
    label: "Tag",
    path: "/tag",
    icons: tags,
  },
  {
    id: Math.random(),
    label: "Alert",
    path: "/alert",
    icons: alert,
  },
  {
    id: Math.random(),
    label: "Avatar",
    path: "/avatar",
    icons: avatar,
  },
  {
    id: Math.random(),
    label: "Banner",
    path: "/banner",
    icons: banner,
  },
  {
    id: Math.random(),
    label: "Breadcrum",
    path: "/breadCrum",
    icons: breadcrum,
  },
  {
    id: Math.random(),
    label: "Fieldset",
    path: "/fieldset",
    icons: fieldset,
  },
  {
    id: Math.random(),
    label: "Figure",
    path: "/figure",
    icons: figure,
  },
  {
    id: Math.random(),
    label: "FullScreen Toggle",
    path: "/fullScreenToggle",
    icons: fullscreen,
  },
  {
    id: Math.random(),
    label: "Grid Background",
    path: "/gridBackground",
    icons: grid,
  },
  {
    id: Math.random(),
    label: "List Group",
    path: "/listGroup",
    icons: list,
  },
  {
    id: Math.random(),
    label: "Model",
    path: "/model",
    icons: modal,
  },
  {
    id: Math.random(),
    label: "Spinner",
    path: "/spinner",
    icons: spinner,
  },
  {
    id: Math.random(),
    label: "Tabel",
    path: "/tabel",
    icons: table,
  },
  {
    id: Math.random(),
    label: "Text Highlighter",
    path: "/textHighlighter",
    icons: textHighlight,
  },
  {
    id: Math.random(),
    label: "Hooks",
    path: "/hooks",
    icons: hooks,
    subMenu: [
      { id: 1, label: "Submenu 1", path: "/submenu-1" },
      { id: 2, label: "Submenu 2", path: "/submenu-2" },
      { id: 3, label: "Submenu 3", path: "/submenu-3" },
    ],
  },
];

export { routes };
